server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ui
          uri: http://localhost:8081
          predicates:
            - Path=/login/**, /oauth2/**, /logout/**, /error/**, /profile/**

        - id: employee
          uri: lb://EMPLOYEE
          predicates:
          - Path=/employee/**

        - id: hr
          uri: lb://HR
          predicates:
            - Path=/hr/**

        - id: intern
          uri: lb://INTERN
          predicates:
            - Path=/intern/**

          filters:
            - RewritePath=/(?<segment>.*), /${segment}

      # Optional: enable detailed logging for debugging routes
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/thinkitive
        registration:
          keycloak:
            client-id: mvc-client
            client-secret: 9Shpfqgwwmat5DsfKG40EBee8r0lxhis
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/thinkitive
          jwk-set-uri: http://localhost:9090/realms/thinkitive/protocol/openid-connect/certs

