server:
  port: 8081
spring:
  application:
    name: ui
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: mvc-client
            client-secret: 9Shpfqgwwmat5DsfKG40EBee8r0lxhis
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "http://localhost:8081/login/oauth2/code/{registrationId}"

        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/thinkitive